
import 'package:face_app/core/resource/styles/string_app.dart';

import 'image_app.dart';

List iconImage = [
  ImageApp.home,
  ImageApp.clock,
  ImageApp.calendar,
  ImageApp.condo,
  ImageApp.flight,
  ImageApp.calendar,
  ImageApp.condo,
  ImageApp.flight,
  ImageApp.home,
  ImageApp.clock,
  ImageApp.calendar,
  ImageApp.condo,
  ImageApp.flight,
  ImageApp.plate,
  ImageApp.bg,
  ImageApp.home,
];

List names = [
  StringApp.home,
  StringApp.airline,
  StringApp.all,
  StringApp.features,
  StringApp.going,
  StringApp.tours,
  StringApp.home,
  StringApp.home,
  StringApp.airline,
  StringApp.all,
  StringApp.features,
  StringApp.going,
  StringApp.theReturn,
  StringApp.tours,
  StringApp.home,
  StringApp.home,
];
List imageA = [
  ImageApp.aeroplane,
  ImageApp.girlTravel,
  ImageApp.splash,
  ImageApp.bg,
  ImageApp.n,
  ImageApp.aeroplane,
  ImageApp.girlTravel,
  ImageApp.bg,
  ImageApp.n,
  ImageApp.aeroplane,
  ImageApp.girlTravel,
  ImageApp.aeroplane,
  ImageApp.aeroplane,
  ImageApp.girlTravel,
  ImageApp.bg,
  ImageApp.n,
  ImageApp.aeroplane,
  ImageApp.girlTravel,
  ImageApp.aeroplane,
  ImageApp.aeroplane,
  ImageApp.girlTravel,
  ImageApp.bg,
  ImageApp.n,
  ImageApp.aeroplane,
  ImageApp.girlTravel,
  ImageApp.aeroplane,
  ImageApp.girlTravel,
  ImageApp.splash,
  ImageApp.girlTravel,
  ImageApp.splash,
  ImageApp.bg,
  ImageApp.n,
  ImageApp.aeroplane,
  ImageApp.girlTravel,
];
List imageB = [
  ImageApp.aeroplane,
  ImageApp.girlTravel,
  ImageApp.splash,
  ImageApp.girlTravel,
  ImageApp.splash,
  ImageApp.bg,
  ImageApp.n,
  ImageApp.aeroplane,
  ImageApp.girlTravel,
  ImageApp.aeroplane,
  ImageApp.girlTravel,
  ImageApp.aeroplane,
  ImageApp.aeroplane,
  ImageApp.girlTravel,
  ImageApp.aeroplane,
  ImageApp.girlTravel,
  ImageApp.splash,
  ImageApp.bg,
  ImageApp.n,
  ImageApp.aeroplane,
  ImageApp.girlTravel,
  ImageApp.bg,
  ImageApp.n,
  ImageApp.aeroplane,
  ImageApp.girlTravel,
  ImageApp.aeroplane,
  ImageApp.aeroplane,
  ImageApp.girlTravel,
  ImageApp.bg,
  ImageApp.n,

  ImageApp.bg,
  ImageApp.n,
  ImageApp.aeroplane,
  ImageApp.girlTravel,


];
